### ISSUE TITLE
Sample and Shift Foraging Behaviour 

### ISSUE THREAD

**Issue by Ferne-Kotlyar** [adriengivry/hummingbird-foraging-strategies-web-app#1]
Felipe wants a version of the SnS bird that after taking nectar from the original flower, only stops at one other flower (instead of as many flowers as possible until it finds what it wants).

**Comment by adriengivry** [comment]
We could address that by adding a parameter to the _Sample & Shift_ bird to set a maximum amount of flowers it can sample in a single patch.

**Comment by adriengivry** [comment]
Fixed in https://github.com/Ferne-Kotlyar/hummingbird-foraging-strategies-web-app/commit/53fa60a826ddf60fe89e96d45d1718d4721fcef9
